backend:
  name: github
  repo: aboelkassem/blog
  branch: master
  accept_roles:
    - admin
    - editor
    - author
    - guest

site_url: https://blog.aboelkassem.com
display_url: https://blog.aboelkassem.com
logo_url: https://blog.aboelkassem.com/icons/icon-512x512.png
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Author", name: "author", widget: "string", default: "aboelkassem"}
      - {label: "Author Link", name: "authorLink", widget: "string", default: "https://twitter.com/aboel_kassem"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover", name: "cover", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Meta Title", name: "metaTitle", widget: "string"}
      - {label: "Meta Description", name: "metaDescription", widget: "text"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "pages"
    label: "Pages"
    files:
    - file: "src/pages/about/index.md"
      label: "About Page"
      name: "about"
      fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
        - {label: "Image", name: "image", widget: "image"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Subtitle", name: "subtitle", widget: "string"}
        - {label: "Author", name: "author", widget: "string"}
        - {label: "Slug", name: "slug", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
        - {label: "Meta Title", name: "metaTitle", widget: "string"}
        - {label: "Meta Description", name: "metaDescription", widget: "text"}
    - file: "src/pages/contact/index.md"
      label: "Contact Page"
      name: "contact"
      fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Slug", name: "slug", widget: "string"}
        - {label: "Subtitle", name: "subtitle", widget: "string"}
        - {label: "Meta Title", name: "metaTitle", widget: "string"}
        - {label: "Meta Description", name: "metaDescription", widget: "text"}
